### ISSUE TITLE
SSH Session pool: Panic if connection failed

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#315]
# Issue Type

## Description

Got a panic that kills Yorc if SSH connection fails

```
Feb 13 10:45:23 node1 yorc[4734]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 13 10:45:23 node1 yorc[4734]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f80d3]
Feb 13 10:45:23 node1 yorc[4734]: goroutine 109 [running]:
Feb 13 10:45:23 node1 yorc[4734]: github.com/ystia/yorc/helper/sshutil.(*pool).getConn(0x26a9700, 0xc000456120, 0x16, 0xc00003bc60, 0xd, 0xc000233d40, 0xd)
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/helper/sshutil/session_pool.go:149 +0x213
Feb 13 10:45:23 node1 yorc[4734]: github.com/ystia/yorc/helper/sshutil.(*pool).openSession(0x26a9700, 0xc00044ca60, 0x0, 0xc0006f5a98, 0x40c2b8)
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/helper/sshutil/session_pool.go:48 +0x259
Feb 13 10:45:23 node1 yorc[4734]: github.com/ystia/yorc/helper/sshutil.(*SSHClient).newSession(0xc00044ca60, 0xc0004bce10, 0x9, 0xc0006f5af0)
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/helper/sshutil/sshutil.go:110 +0x3b
Feb 13 10:45:23 node1 yorc[4734]: github.com/ystia/yorc/helper/sshutil.(*SSHClient).GetSessionWrapper(0xc00044ca60, 0xc00003bc30, 0xc0006f5d40, 0x1)
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/helper/sshutil/sshutil.go:75 +0x49
Feb 13 10:45:23 node1 yorc[4734]: github.com/ystia/yorc/prov/slurm.(*defaultExecutor).createNodeAllocation(0xc00000c298, 0x1a12fa0, 0xc0001e4660, 0xc00000c1e8, 0xc000083110, 0xc0003bee80, 0x36, 0xc00003b314, 0x7,
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/prov/slurm/executor.go:212 +0x2bc
Feb 13 10:45:23 node1 yorc[4734]: github.com/ystia/yorc/prov/slurm.(*defaultExecutor).createInfrastructure.func1.1(0x8, 0x1892a18)
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/prov/slurm/executor.go:151 +0x76
Feb 13 10:45:23 node1 yorc[4734]: github.com/ystia/yorc/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0001e45d0, 0xc0000d0780)
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
Feb 13 10:45:23 node1 yorc[4734]: created by github.com/ystia/yorc/vendor/golang.org/x/sync/errgroup.(*Group).Go
Feb 13 10:45:23 node1 yorc[4734]: /home/travis/gopath/src/github.com/ystia/yorc/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
Feb 13 10:45:23 node1 systemd[1]: yorc.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```
 
## Steps to reproduce the issue

1. Create a Slurm infrastructure with invalid credentials
2. Try to allocate a Slurm node

## Additional environment details (infrastructure implied: AWS, OpenStack, etc.)

Slurm

## Output of `yorc version`

3.1.1

## Priority

High

**Comment by loicalbertin** [comment]
Merged into 3.1.2 release and ported to develop (3.2.0-M2)
