### ISSUE TITLE
Support OpenStack authentication with user domain (Keystone v3)

### ISSUE THREAD

**Issue by trihoangvo** [ystia/yorc#355]
**Is your feature request related to a problem? Please describe.**

At the moment, Yorc authenticates to Keystone API v2 using `tenant_name`:
https://github.com/ystia/yorc/blob/develop/prov/terraform/openstack/generator.go#L81

However, OpenStack in recent years uses Keystone API v3 that uses `USER_DOMAIN_NAME` & `PROJECT_ID` instead of `tenant_name`.

**Describe the solution you'd like**

Yorc should support Keystone API v3 with domain and project as follows:
```
OS_USERNAME
OS_PASSWORD
OS_PROJECT_NAME
OS_PROJECT_ID
OS_USER_DOMAIN_NAME
OS_AUTH_URL
```

**Describe alternatives you've considered**

no alternative solutions

**Additional context**

Error log in a4c when Yorc authenticates to OpenStack that requires Keystone v3

> [2019-03-28 11:57:46] [] [Compute] Status for node "Compute", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [Compute] Attribute value for node "Compute", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [Compute] Attribute value for node "Compute", instance "0" changed to "Compute"
  [2019-03-28 11:57:46] [] [Compute] Attribute value for node "Compute", instance "0" changed to "Compute-0"
  [2019-03-28 11:57:46] [] [FIPCompute] Status for node "FIPCompute", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "FIPCompute-0"
  [2019-03-28 11:57:46] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "FIPCompute"
  [2019-03-28 11:57:46] [] [FIPCompute] Status for node "FIPCompute", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "FIPCompute"
  [2019-03-28 11:57:46] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "FIPCompute-0"
  [2019-03-28 11:57:46] [] [Welcome] Status for node "Welcome", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [Welcome] Attribute value for node "Welcome", instance "0" changed to "initial"
  [2019-03-28 11:57:46] [] [Welcome] Attribute value for node "Welcome", instance "0" changed to "Welcome"
  [2019-03-28 11:57:46] [] [Welcome] Attribute value for node "Welcome", instance "0" changed to "Welcome-0"
  [2019-03-28 11:57:46] [install] [] Status for workflow "install" changed to "initial"
  [2019-03-28 11:57:46] [install] [] Status for workflow "install" changed to "running"
  [2019-03-28 11:57:46] [install] [] Status for deployment "test-Environment" changed to "deployment_in_progress"
  [2019-03-28 11:57:46] [install] [] Start processing workflow step install:FIPCompute_install
  [2019-03-28 11:57:46] [install] [FIPCompute] Status for workflow step "FIPCompute_install" changed to "INITIAL"
  [2019-03-28 11:57:46] [install] [FIPCompute] Status for task execution "4bf73f94-166c-4be1-8b8d-9f412f415ce5-0" changed to "INITIAL"
  [2019-03-28 11:57:46] [install] [FIPCompute] Status for workflow step "FIPCompute_install" changed to "RUNNING"
  [2019-03-28 11:57:47] [install] [FIPCompute] Status for task execution "4bf73f94-166c-4be1-8b8d-9f412f415ce5-0" changed to "RUNNING"
  [2019-03-28 11:57:47] [install] [FIPCompute] Status for node "FIPCompute", instance "0" changed to "creating"
  [2019-03-28 11:57:47] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "creating"
  [2019-03-28 11:57:47] [install] [FIPCompute] Remote configuring the infrastructure
  [2019-03-28 11:57:47] [install] [FIPCompute] Applying the infrastructure
  [2019-03-28 11:57:47] [install] [FIPCompute] 
Initializing the backend...
Successfully configured the backend "consul"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
  [2019-03-28 11:57:47] [install] [FIPCompute] 
Error: Error running plan: 1 error(s) occurred:
provider.openstack: You must provide exactly one of DomainID or DomainName to authenticate by Username
  [2019-03-28 11:57:47] [install] [FIPCompute] Status for workflow step "FIPCompute_install" changed to "ERROR"
  [2019-03-28 11:57:47] [install] [FIPCompute] Status for task execution "4bf73f94-166c-4be1-8b8d-9f412f415ce5-0" changed to "ERROR"
  [2019-03-28 11:57:47] [install] [FIPCompute] Status for node "FIPCompute", instance "0" changed to "error"
  [2019-03-28 11:57:47] [] [FIPCompute] Attribute value for node "FIPCompute", instance "0" changed to "error"
  [2019-03-28 11:57:47] [install] [] Error 'exit status 1
Failed to apply the infrastructure changes via terraform
github.com/ystia/yorc/v3/prov/terraform.(*defaultExecutor).applyInfrastructure
/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:293
github.com/ystia/yorc/v3/prov/terraform.(*defaultExecutor).installNode
/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:107
github.com/ystia/yorc/v3/prov/terraform.(*defaultExecutor).ExecDelegate
/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:79
github.com/ystia/yorc/v3/tasks/workflow.(*step).runActivity.func1
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:266
github.com/ystia/yorc/v3/tasks/workflow.(*step).runActivity
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:267
github.com/ystia/yorc/v3/tasks/workflow.(*step).run.func3
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:210
github.com/ystia/yorc/v3/tasks/workflow.(*step).run
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:227
github.com/ystia/yorc/v3/tasks/workflow.(*worker).runWorkflowStep
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:729
github.com/ystia/yorc/v3/tasks/workflow.(*worker).runDeploy
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:554
github.com/ystia/yorc/v3/tasks/workflow.(*worker).handleExecution
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:210
github.com/ystia/yorc/v3/tasks/workflow.(*worker).Start.func1
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:83
runtime.goexit
/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337' happened in workflow "install".
  [2019-03-28 11:57:47] [install] [] The workflow install step FIPCompute_install ended with error:exit status 1
Failed to apply the infrastructure changes via terraform
github.com/ystia/yorc/v3/prov/terraform.(*defaultExecutor).applyInfrastructure
/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:293
github.com/ystia/yorc/v3/prov/terraform.(*defaultExecutor).installNode
/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:107
github.com/ystia/yorc/v3/prov/terraform.(*defaultExecutor).ExecDelegate
/home/travis/gopath/src/github.com/ystia/yorc/prov/terraform/executor.go:79
github.com/ystia/yorc/v3/tasks/workflow.(*step).runActivity.func1
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:266
github.com/ystia/yorc/v3/tasks/workflow.(*step).runActivity
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:267
github.com/ystia/yorc/v3/tasks/workflow.(*step).run.func3
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:210
github.com/ystia/yorc/v3/tasks/workflow.(*step).run
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/step.go:227
github.com/ystia/yorc/v3/tasks/workflow.(*worker).runWorkflowStep
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:729
github.com/ystia/yorc/v3/tasks/workflow.(*worker).runDeploy
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:554
github.com/ystia/yorc/v3/tasks/workflow.(*worker).handleExecution
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:210
github.com/ystia/yorc/v3/tasks/workflow.(*worker).Start.func1
/home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:83
runtime.goexit
/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337: Failed to apply the infrastructure changes via terraform: exit status 1
  [2019-03-28 11:57:47] [install] [] Workflow "install" ended in error
  [2019-03-28 11:57:47] [install] [] Status for workflow "install" changed to "failed"
  [2019-03-28 11:57:47] [install] [] Status for deployment "test-Environment" changed to "deployment_failed"
  [2019-03-28 11:57:47] [] [] Deployment failed
java.lang.Exception: Deployment failed
at org.ystia.yorc.alien4cloud.plugin.DeployTask.run(DeployTask.java:188)
at org.ystia.yorc.alien4cloud.plugin.TaskManager.nextWork(TaskManager.java:89)
at org.ystia.yorc.alien4cloud.plugin.TaskManager$WorkThread.run(TaskManager.java:141)

**Comment by loicalbertin** [comment]
Hi @trihoangvo, 

Thanks for this report. You are right we should consider adding those configuration properties.
As a workaround you can export `OS_*` environment variables before running the Yorc process, there will be automatically detected and used.

**Comment by trihoangvo** [comment]
will fix this during our evaluation and send merge request

**Comment by loicalbertin** [comment]
Thank you @trihoangvo for your contribution!
